version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Cray-HPE/CMS-core-product-support"
    labels:
      - "github-actions-deps"
      - "dependabot"
    open-pull-requests-limit: 3

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Cray-HPE/CMS-core-product-support"
    labels:
      - "python-deps"
      - "dependabot"
    open-pull-requests-limit: 3
