---
apiVersion: v1
name: cray-product-catalog
version: @VERSION@
description: Catalog of Cray Shasta add-on products
home: "scms/cray-product-install-charts"
keywords:
- cray
- shasta
maintainers:
- email: randy.kleinman@hpe.com
  name: rkleinman
