{{/*
MIT License

(C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-product-catalog-restore
  namespace: services
  annotations:
    "helm.sh/hook": post-upgrade,post-rollback
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: cray-product-catalog
      restartPolicy: Never
      containers:
      - name: create-catalog-configmap
        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
        command: ["/bin/sh"]
        args:
          - "-c"
          - "kubectl delete cm -n services cray-product-catalog &&
              kubectl get cm -n services cpc-backup -o yaml |
              yq eval '.metadata.name = \"cray-product-catalog\"' - |
              yq eval 'del(.metadata.resourceVersion, .metadata.uid, .metadata.annotations, .metadata.creationTimestamp, .metadata.selfLink, .metadata.managedFields)' - |
              kubectl create -f - && kubectl delete cm -n services cpc-backup"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-product-catalog-backup
  namespace: services
  annotations:
    "helm.sh/hook": pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: cray-product-catalog
      restartPolicy: Never
      containers:
      - name: create-catalog-configmap
        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
        command: ["/bin/sh"]
        args:
          - "-c"
          - "kubectl get cm -n services cray-product-catalog -o yaml |
              yq eval '.metadata.name = \"cpc-backup\"' - |
              yq eval 'del(.metadata.resourceVersion, .metadata.uid, .metadata.annotations, .metadata.creationTimestamp, .metadata.selfLink, .metadata.managedFields)' - |
              kubectl create -f -"


---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-my-job
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - args:
          - -c
          - /usr/bin/catalog_migrate
          command:
          - /bin/sh
          env:
          - name: CONFIG_MAP
            value: {{ .Values.migration.configMap }}
          - name: CONFIG_MAP_NAMESPACE
            value: {{ .Values.migration.configMapNamespace }}
          image: "{{ .Values.migration.image.repository }}:{{ .Values.global.appVersion }}"
          imagePullPolicy: IfNotPresent
          name: migrate-catalog
      restartPolicy: Never
      serviceAccount: {{ .Values.migration.serviceAccount }}
      serviceAccountName: {{ .Values.migration.serviceAccount }}

