{{/*
MIT License

(C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-product-catalog-restore
  namespace: services
  annotations:
    "helm.sh/hook": post-upgrade,post-rollback
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: cray-product-catalog
      restartPolicy: Never
      containers:
      - name: create-catalog-configmap
        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
        command: ["/bin/sh"]
        args:
          - "-c"
          - "for config_map in `kubectl get cm  -n services -l type=cray-product-catalog |
            grep cpc-backup | cut -d' ' -f1` ;
            do
              restore_config_map_name=`echo ${config_map/cpc-backup/cray-product-catalog}`;
              kubectl get cm -n services ${config_map} -o yaml |
              yq eval \".metadata.name = \"${restore_config_map_name}\"\" - |
              yq eval 'del(.metadata.resourceVersion, .metadata.uid, .metadata.annotations,
              .metadata.creationTimestamp, .metadata.selfLink, .metadata.managedFields)' - |
              kubectl apply -f - && kubectl delete cm -n services ${config_map}
            done"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-product-catalog-backup
  namespace: services
  annotations:
    "helm.sh/hook": pre-upgrade,pre-rollback
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: cray-product-catalog
      restartPolicy: Never
      containers:
      - name: create-catalog-configmap
        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
        command: ["/bin/sh"]
        args:
          - "-c"
          - "for config_map in `kubectl get cm  -n services -l type=cray-product-catalog |
            cut -d' ' -f1 | tail -n  +2`;
            do
              backup_config_map_name=`echo ${config_map/cray-product-catalog/cpc-backup}`;
              kubectl get cm -n services ${config_map} -o yaml |
              yq eval \".metadata.name = \"${restore_config_map_name}\"\" - |
              yq eval 'del(.metadata.resourceVersion, .metadata.uid, .metadata.annotations,
              .metadata.creationTimestamp, .metadata.selfLink, .metadata.managedFields)' - |
              kubectl apply -f -
            done"