---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cray-product-catalog
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "update", "patch", "delete"]
