name: Build Docker Image
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
      - release/**
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    # env:
    #   CONTEXT_PATH: docker.io/alpine/git/1.0.15
    #   DOCKER_REPO: artifactory.algol60.net/csm-docker/stable/docker.io/alpine/git
    #   DOCKER_TAG: 1.0.15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Calculate version
        uses: docker://gittools/gitversion:5.6.6
        with:
          args: '/output buildserver'

      - name: build-sign-scan
        uses: Cray-HPE/github-actions/build-sign-scan@main
        with:
          # Only push on main builds
          # docker_push: ${{ github.ref == 'refs/heads/main' }}
          docker_push: true
          context_path: ${{ env.CONTEXT_PATH }}
          docker_repo: ${{ env.DOCKER_REPO }}
          docker_tag: ${{ steps.gitversion.outputs.semVer }}
          artifactory_algol60_token: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
          cosign_gcp_project_id: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
          cosign_gcp_sa_key: ${{ secrets.COSIGN_GCP_SA_KEY }}
          cosign_key: ${{ secrets.COSIGN_KEY }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          github_sha: $GITHUB_SHA
