name: Changelog Checker
on:
  pull_request: 

# Workflow Jobs
jobs:
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v13.1
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          files: |
            CHANGELOG.md

      - name: Ensure the changelog file has changed
        if: steps.changed-files.outputs.any_modified != 'true'
        run: |

          echo "Changelog has not been modified. Please add a changelog entry in accordance with https://keepachangelog.com"
          exit 1;