# Create a new release
name: Create Release

on:
  push:
    tags:
    - 'v*'

jobs:

  # Build and upload artifacts
  build-artifacts:
    # FIXME: For now, have to specify a ref for calling reusable workflows, see https://github.community/t/ref-head-in-reusable-workflows/203690/30
    uses: Cray-HPE/cray-product-catalog/.github/workflows/build-artifacts.yml@develop
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      ARTIFACTORY_ALGOL60_JFROG_CLI_CONFIGURATION: ${{ secrets.ARTIFACTORY_ALGOL60_JFROG_CLI_CONFIGURATION }}
      ARTIFACTORY_ALGOL60_USERNAME: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
      ARTIFACTORY_ALGOL60_TOKEN: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
      COSIGN_GCP_PROJECT_ID: ${{ secrets.COSIGN_GCP_PROJECT_ID }}
      COSIGN_GCP_SA_KEY: ${{ secrets.COSIGN_GCP_SA_KEY }}
      COSIGN_KEY: ${{ secrets.COSIGN_KEY }}

  # Create a GH release and reference the artifacts and changes
  create-gh-release:
    runs-on: ubuntu-latest
    needs:
      - build-artifacts
    permissions:
      contents: write

    steps:
      - run: |
          echo ${{ needs.build-artifacts.outputs.semVer }}
          echo ${{ needs.build-artifacts.outputs.image-version }}
          echo ${{ needs.build-artifacts.outputs.chart-version }}
          echo ${{ needs.build-artifacts.outputs.py-version }}
          echo ${{ needs.build-artifacts.outputs.is-stable }}
          echo ${{ needs.build-artifacts.outputs.build-date-time }}
          echo ${{ needs.build-artifacts.outputs.image }}
          echo ${{ needs.build-artifacts.outputs.image_url }}
          echo ${{ needs.build-artifacts.outputs.chart }}
          echo ${{ needs.build-artifacts.outputs.chart_url }}
          echo ${{ needs.build-artifacts.outputs.pymod }}
          echo ${{ needs.build-artifacts.outputs.pymod_url }}

      - uses: actions/checkout@v2

      # This action assumes that the release notes are the second header in the
      # Keep a Changelog format, which skips the "Unreleased" section. Therefore,
      # it will not work for prereleases where a new section has not been created
      # like alpha releases on the develop branch, or one-off releases from
      # feature branches
      - name: Extract release notes
        if: needs.build-artifacts.outputs.is-stable == 'stable'
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1.11.0
        with:
          changelog_file: CHANGELOG.md

      - name: Render release template
        uses: chuhlomin/render-template@v1.4
        id: template
        with:
          template: .github/templates/release.md.tmpl
          vars: |
            releaseNotes: ${{ steps.extract-release-notes.outputs.release_notes }}
            isStable: "${{ needs.build-artifacts.outputs.is-stable }}"
            image: "${{ needs.build-artifacts.outputs.image }}"
            imageUrl: "${{ needs.build-artifacts.outputs.image_url }}"
            chart: "${{ needs.build-artifacts.outputs.chart }}"
            chartUrl: "${{ needs.build-artifacts.outputs.chart_url }}"
            pymod: "${{ needs.build-artifacts.outputs.pymod }}"
            pymodUrl: "${{ needs.build-artifacts.outputs.pymod_url }}"
            runUrl: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            runID: ${{ github.run_id }}

      - uses: ncipollo/release-action@v1
        if: needs.build-artifacts.outputs.is-stable == 'stable'
        with:
          generateReleaseNotes: true
          prerelease: false
          body: ${{ steps.template.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        if: needs.build-artifacts.outputs.is-stable == 'unstable'
        with:
          generateReleaseNotes: true
          prerelease: true
          body: ${{ steps.template.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
