# See https://github.com/thomaseizinger/github-action-gitflow-release-workflow
# This should only be dispatched from the 'develop' or a 'hotfix' branch.
name: "Draft New Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The (SemVer) version to release:'
        required: true

jobs:
  create-release-draft:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.auto-commit-action.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: ${{ github.event.inputs.version }}

      # If anything else needs to be done (bump version files etc) to generate
      # a release in this repository, do it here

      - name: Push new branch
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: "[bot] Prepare release ${{ github.event.inputs.version }}"
          commit_user_name: "github-actions[bot]"
          branch: release/${{ github.event.inputs.version }}

  create-release-pr:
    name: "Create a PR for the new release branch"
    runs-on: ubuntu-latest
    needs: create-release-draft
    env:
      GITHUB_AUTH_APP_ID: 129003
    permissions:
      #   actions: write
      pull-requests: write
      #   contents: read
      #   repository-projects: write
    steps:

      - name: Get auth token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.ALGOL60_GITHUB_READONLY_APP }}
          app-id: ${{env.GITHUB_AUTH_APP_ID}}

      - name: Create Pull Request (release/${{ github.event.inputs.version }} -> master)
        id: cpr
        uses: thomaseizinger/create-pull-request@1.2.2
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
        with:
          head: release/${{ github.event.inputs.version }}
          base: master
          title: '[autogenerated] Create release version ${{ github.event.inputs.version  }}'
          reviewers: ${{ github.actor }}
          labels: 'github-actions, gitflow-maintenance'
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            The bots committed changes the changelog and bumped versions (if applicable) in this commit: ${{ needs.create-release-draft.outputs.commit }}.

            Merging this PR will automatically create a GitHub release and create a PR with an updated CSM manifest (if applicable).
            See .github/workflows/publish-new-release.yml.

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.html_url }}"
