# See https://github.com/thomaseizinger/github-action-gitflow-release-workflow
# This should only be dispatched from the 'develop' or a 'hotfix' branch.
name: "Draft New Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The (SemVer) version to release:'
        required: true

jobs:
  create-release-draft:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.auto-commit-action.outputs.commit_hash }}
      release-branch: ${{ steps.create-branch.outputs.release-branch }}
      pr-number: ${{ steps.cpr.outputs.number }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Create a new release branch
        id: create-branch
        run: |
          git checkout -b release/${{ github.event.inputs.version }}
          echo ::set-output name=release-branch::$(echo release/${{ github.event.inputs.version }})

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: ${{ github.event.inputs.version }}

      # If anything else needs to be done (bump version files etc) to generate
      # a release in this repository, do it here
      - name: Push new branch
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: "[bot] Prepare release ${{ github.event.inputs.version }}"
          commit_user_name: "github-actions[bot]"
          branch: release/${{ github.event.inputs.version }}

      - name: Create Pull Request (release/${{ github.event.inputs.version }} -> master)
        id: cpr
        uses: thomaseizinger/create-pull-request@1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: ${{ steps.create-branch.outputs.release-branch }}
          base: master
          title: '[autogenerated] Create release version ${{ github.event.inputs.version  }}'
          reviewers: ${{ github.actor }}
          labels: 'github-actions, gitflow-maintenance'
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to your manual trigger of the [draft release workflow #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            The bots updated the changelog and bumped versions (if applicable) in this commit: ${{ needs.create-release-draft.outputs.commit }}.

            Merging this PR will automatically create a new GitHub release of version ${{ github.event.inputs.version }} and create a PR with an updated CSM manifest (if applicable).
            See .github/workflows/publish-new-release.yml.

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.html_url }}"

  trigger-release-workflows:
    name: "Trigger Release Branch Workflows"
    runs-on: self-hosted
    needs:
      - create-release-draft
    env:
      GITHUB_AUTH_APP_ID: 129003
    permissions:
      actions: write
      pull-requests: write
      contents: read
      repository-projects: write

    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.create-release-draft.outputs.release-branch }}

      - name: Get auth token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.ALGOL60_GITHUB_READONLY_APP }}
          app-id: ${{env.GITHUB_AUTH_APP_ID}}

      - name: Trigger Pull request and branch push workflows
        run: |
          echo "Triggering build-artifacts.yml for PR #${PR_NUMBER}"
          gh workflow run build-artifacts.yml --ref ${BRANCH}
        env:
          PR_NUMBER: ${{ needs.create-release-draft.outputs.pr-number }}
          BRANCH: ${{ needs.create-release-draft.outputs.release-branch }}
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}

