#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
name: Gitflow Merge Back
on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  merge-to-develop:
    # this job will only run if the PR has been merged, not just closed
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Get auth token for PR creation
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.CSM_GITFLOW_MERGEBACK_BOT_APP_KEY }}
          app-id: ${{ secrets.CSM_GITFLOW_MERGEBACK_BOT_APP_ID }}

      - uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ steps.get-token.outputs.token }}

      # https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another
      - name: Reset target branch
        run: |
          git fetch origin master:master
          git reset --hard master

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.get-token.outputs.token }}
          branch: mergeback-master-${{ github.event.pull_request.head.ref }}
          branch-suffix: timestamp
          base: develop
          delete-branch: true
          title: "[chore] Master -> Develop from PR ${{ github.repository }}#${{ github.event.pull_request.number }} (${{ github.event.pull_request.head.ref }})"
          signoff: true
          assignees: ${{ github.actor }}
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "${{ github.event.pull_request.user.login }} <${{ github.event.pull_request.user.login }}@users.noreply.github.com>"
          labels: |
            gitflow-maintenance

          commit-message: >
            Autogenerated gitflow merge back from PR #${{ github.event.pull_request.number }}:

            * Head Branch: ${{ github.event.pull_request.head.ref }}

            * Autogenerated-by: [${{ github.workflow }} workflow #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          body: >
            Autogenerated gitflow merge back from PR #${{ github.event.pull_request.number }}:

            * Head Branch: ${{ github.event.pull_request.head.ref }}

            * Requested-by: @${{ github.event.pull_request.user.login }}

            * Autogenerated-by: [${{ github.workflow }} workflow #${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          reviewers: |
            Cray-HPE/CMS-core-product-support

      - name: Generated Pull Request Info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ steps.get-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: merge
