name: Create GitHub Release

on:
  push:
    tags:
    - 'v*'

jobs:

  create-gh-release:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Get semver tool; determine prerelease or not
      id: prerelease
      run: |
        wget -O ./semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
        chmod +x ./semver
        export RELEASE_VERSION=${GITHUB_REF#refs/*/v}
        PRERELEASE=$(./semver get prerel ${RELEASE_VERSION})
        if [[ "${PRERELEASE}" = "" ]]; then
          echo ::set-output name=gh_prerelease::$(echo false)
        else
          echo ::set-output name=gh_prerelease::$(echo true)
        fi

    - uses: ncipollo/release-action@v1
      if: ${{ steps.prerelease.outputs.gh_prerelease == "false" }}
      with:
        generateReleaseNotes: true
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ncipollo/release-action@v1
      if: ${{ steps.prerelease.outputs.gh_prerelease == "true" }}
      with:
        generateReleaseNotes: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}