
name: Add artifact information to PR
on:
  pull_request: 

# Globals
env:

  # Package/artifact names
  IMAGE_NAME: cray-product-catalog-update
  CHART_NAME: cray-product-catalog
  PYMOD_NAME: cray-product-catalog

# Workflow Jobs
jobs:
  update-pr-with-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Wait for push build to succeed and upload deploy script
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: publish-deploy-script
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Wait a while for the github api to report the workflow/artifact
        run: |
          # Kinda expected the previous action to do this, but it doesn't always
          # end up that way.
          sleep 60;

      - name: Download deploy script artifact
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-artifacts.yml
          workflow_conclusion: success
          pr: ${{ github.event.pull_request.number }}
          name: deploy-script.sh

      - name: Download artifacts.json
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-artifacts.yml
          workflow_conclusion: success
          pr: ${{ github.event.pull_request.number }}
          name: artifacts.json

      - name: Read artifacts JSON in
        id: set-json-vars
        run: |
          JSON=$(cat ./artifacts.json)
          echo "::set-output name=artifacts::${JSON//'%'/'%25'}"

      - name: Inject deploy script into pr artifacts template
        if: steps.wait-for-build.outputs.conclusion == 'success'
        run: |
          sed -i -e '/# script #/r./deploy-script.sh' .github/templates/pr-artifacts.md.tmpl

      - name: Render artifacts comment template
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: chuhlomin/render-template@v1.4
        id: template
        with:
          template: .github/templates/pr-artifacts.md.tmpl
          vars: |
            deployScript: "${{ steps.scriptvar.outputs.deploy_script }}"
            srcBranch: ${{ github.event.pull_request.head.ref }}
            commit: ${{ github.event.pull_request.head.sha}}
            image: "${{fromJson(steps.set-json-vars.outputs.artifacts).image}}"
            imageUrl: "${{fromJson(steps.set-json-vars.outputs.artifacts).image_url}}"
            chartName: "${{ env.CHART_NAME }}"
            chart: "${{fromJson(steps.set-json-vars.outputs.artifacts).chart}}"
            chartUrl: "${{fromJson(steps.set-json-vars.outputs.artifacts).chart_url}}"
            pymod: "${{fromJson(steps.set-json-vars.outputs.artifacts).pymod}}"
            pymodUrl: "${{fromJson(steps.set-json-vars.outputs.artifacts).pymod_url}}"

      - name: Create commit comment
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: peter-evans/commit-comment@v1
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          body: ${{ steps.template.outputs.result }}
