# Update the CHANGELOG.md file and do other release preparations. This happens
# when a pull request is opened against the master branch, either from
# a release or hotfix branch.
name: "Prepare for Release"

on:
  pull_request_target:
    branch: master
    types: [ opened ]

jobs:
  prepare-for-release:
    name: "Update changelog and version files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          env | sort
      # - name: Update changelog
      #   uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
      #   with:
      #     tag: ${{ github.event.inputs.version }}

      # # If anything else needs to be done (bump version files etc) to generate
      # # a release in this repository, do it here

      # - name: Push Changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   id: auto-commit-action
      #   with:
      #     commit_message: "[bot] Prepare release ${{ github.event.inputs.version }}"
      #     commit_user_name: "github-actions[bot]"
      #     branch: release/${{ github.event.inputs.version }}

