# Update the CHANGELOG.md file and do other release preparations. This happens
# when a pull request is opened against the master branch, either from
# a release or hotfix branch.
name: "Prepare for Release"

on:
  pull_request:
    branches:
      - master
    types: [ opened ]

jobs:
  prepare-for-release:
    name: "Update changelog and version files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: find version from branch name
        id: get-version
        run: |
          echo ${{ github.head_ref }}
          echo ${IS_RELEASE}
          echo ${IS_HOTFIX}
          if [[ "${IS_RELEASE}"" = "true" ]]; then
            VERSION=${${{ github.head_ref }}##refs/heads/release/}
          else
            VERSION=${${{ github.head_ref }}##refs/heads/hotfix/}
          fi
          echo ::set-output name=version::$(echo ${VERSION})
        env:
          IS_RELEASE: "${{ contains(github.events.pull_request.head.ref, 'release') }}"
          IS_HOTFIX: "${{ contains(github.events.pull_request.head.ref, 'hotfix') }}"

      - run: |
          echo ${{ env.VERSION }}
        env:
          VERSION: ${{ steps.get-version.outputs.version }}

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: ${{ steps.get-version.outputs.version }}

      # # If anything else needs to be done (bump version files etc) to generate
      # # a release in this repository, do it here

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: "[bot] Prepare release ${{ steps.get-version.outputs.version }}"
          commit_user_name: "github-actions[bot]"
          branch: ${{ github.events.pull_request.head.ref }}
