# See https://github.com/thomaseizinger/github-action-gitflow-release-workflow
name: "Publish New Release"

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  release:
    name: Publish new release
    runs-on: self-hosted
    if: github.event.pull_request.merged == true # only merged pull requests trigger this job
    steps:

      - name: Prep build metdata and fetch version
        id: buildprepversion
        uses: Cray-HPE/.github/actions/csm-run-build-prep@v2-csm-run-build-prep

      - name: Create Release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
          tag_name: ${{ steps.buildprepversion.outputs.version }}
          name: v${{ steps.buildprepversion.outputs.version }}
          draft: false
          prerelease: false

      - name: Merge master into dev branch
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: master
          base: dev
          labels: release,github-actions
          title: '[autogenerated] Merge master to dev after release ${{ steps.buildprepversion.outputs.version }}'
          body: |
            This is an autogenerated PR created when a release is created with a merge to master.
            This PR merges the master branch back into dev to ensure that the updates that happened on the release branch, i.e. CHANGELOG and manifest updates are also present on the dev branch.
            
            See ${{ github.event.pull_request.number }}.

      # if needed, you can checkout the latest master here, build artifacts and publish / deploy them somewhere
      # the create-release action has an output `upload_url` output that you can use to upload assets
