# Update the CSM Manifest with artifacts from a given release
name: "Update CSM Manifest"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to update to in CSM manifest'
        required: true
      csm-branch:
        description: 'branch in the Cray-HPE/csm repo to update'
        required: true
        default: 'main'
      csm-manifest-path:
        description: 'relative path to the CSM manifest to update'
        required: true
        default: 'manifests/sysmgmt.yaml'
      create-pr:
        type: boolean
        description: 'create a pull request in the Cray-HPE/csm repo'
        required: true
        default: true
      create-pr-draft:
        type: boolean
        description: 'make the pull request a draft PR'
        required: false
        default: true

jobs:

  update-csm-manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout CSM repo
        uses: actions/checkout@v2
        with:
          repository: Cray-HPE/csm
          path: './csm'
          ref: ${{ inputs.csm-branch }}

      - name: Update manifest helm chart version
        uses: mikefarah/yq@master
        with:
          cmd: yq eval --inplace 'with(.spec.charts[] | select(.name == "cray-product-catalog") ; .version = "strenv(VERSION)")' ${{ env.MANIFEST_PATH }}
        env:
          VERSION: ${{ inputs.version }}
          MANIFEST_PATH: ./csm/${{ inputs.csm-manifest-path }}

      - name: Review Manifest File
        run: |
          cat ./csm/${{ inputs.csm-manifest-file }}

      - uses: EndBug/add-and-commit@v8
        with:
          message: "Update manifest for ${{ github.repository }} release version: ${{ inputs.version }}"
          add: "${{ inputs.csm-manifest-path }}"
          cwd: './csm/'
          pathspec_error_handling: exitImmediately
          push: true
          new_branch: cray-product-catalog/release-${{ inputs.version }}
          committer_name: github-actions[bot]
          committer_email: noreply@github.com
